is_day(x::TimeType, day::Integer) = Dates.day(x) == day
is_day_between(x::TimeType, day_start::Integer, day_end::Integer) = Dates.day(x) >= day_start && Dates.day(x) <= day_end

is_year_between(x::TimeType, year_start::Integer, year_end::Integer) =
    Dates.year(x) >= year_start && Dates.year(x) <= year_end

is_january(x::TimeType) = Dates.month(x) == Dates.Jan
is_february(x::TimeType) = Dates.month(x) == Dates.Feb
is_march(x::TimeType) = Dates.month(x) == Dates.Mar
is_april(x::TimeType) = Dates.month(x) == Dates.Apr
is_may(x::TimeType) = Dates.month(x) == Dates.May
is_june(x::TimeType) = Dates.month(x) == Dates.Jun
is_july(x::TimeType) = Dates.month(x) == Dates.Jul
is_august(x::TimeType) = Dates.month(x) == Dates.Aug
is_september(x::TimeType) = Dates.month(x) == Dates.Sep
is_october(x::TimeType) = Dates.month(x) == Dates.Oct
is_november(x::TimeType) = Dates.month(x) == Dates.Nov
is_december(x::TimeType) = Dates.month(x) == Dates.Dec

is_monday(x::TimeType) = Dates.dayofweek(x) == Dates.Mon
is_tuesday(x::TimeType) = Dates.dayofweek(x) == Dates.Tue
is_wednesday(x::TimeType) = Dates.dayofweek(x) == Dates.Wed
is_thursday(x::TimeType) = Dates.dayofweek(x) == Dates.Thu
is_friday(x::TimeType) = Dates.dayofweek(x) == Dates.Fri
is_saturday(x::TimeType) = Dates.dayofweek(x) == Dates.Sat
is_sunday(x::TimeType) = Dates.dayofweek(x) == Dates.Sun
is_weekday(x::TimeType) = is_monday(x) || is_tuesday(x) || is_wednesday(x) || is_thursday(x) || is_friday(x)
is_weekend(x::TimeType) = is_saturday(x) || is_sunday(x)

is_first_monday_of_month(x::TimeType) = is_monday(x) && Dates.dayofweekofmonth(x) == 1
is_first_tuesday_of_month(x::TimeType) = is_tuesday(x) && Dates.dayofweekofmonth(x) == 1
is_first_wednesday_of_month(x::TimeType) = is_wednesday(x) && Dates.dayofweekofmonth(x) == 1
is_first_thursday_of_month(x::TimeType) = is_thursday(x) && Dates.dayofweekofmonth(x) == 1
is_first_friday_of_month(x::TimeType) = is_friday(x) && Dates.dayofweekofmonth(x) == 1
is_first_saturday_of_month(x::TimeType) = is_saturday(x) && Dates.dayofweekofmonth(x) == 1
is_first_sunday_of_month(x::TimeType) = is_sunday(x) && Dates.dayofweekofmonth(x) == 1

is_second_monday_of_month(x::TimeType) = is_monday(x) && Dates.dayofweekofmonth(x) == 2
is_second_tuesday_of_month(x::TimeType) = is_tuesday(x) && Dates.dayofweekofmonth(x) == 2
is_second_wednesday_of_month(x::TimeType) = is_wednesday(x) && Dates.dayofweekofmonth(x) == 2
is_second_thursday_of_month(x::TimeType) = is_thursday(x) && Dates.dayofweekofmonth(x) == 2
is_second_friday_of_month(x::TimeType) = is_friday(x) && Dates.dayofweekofmonth(x) == 2
is_second_saturday_of_month(x::TimeType) = is_saturday(x) && Dates.dayofweekofmonth(x) == 2
is_second_sunday_of_month(x::TimeType) = is_sunday(x) && Dates.dayofweekofmonth(x) == 2

is_third_monday_of_month(x::TimeType) = is_monday(x) && Dates.dayofweekofmonth(x) == 3
is_third_tuesday_of_month(x::TimeType) = is_tuesday(x) && Dates.dayofweekofmonth(x) == 3
is_third_wednesday_of_month(x::TimeType) = is_wednesday(x) && Dates.dayofweekofmonth(x) == 3
is_third_thursday_of_month(x::TimeType) = is_thursday(x) && Dates.dayofweekofmonth(x) == 3
is_third_friday_of_month(x::TimeType) = is_friday(x) && Dates.dayofweekofmonth(x) == 3
is_third_saturday_of_month(x::TimeType) = is_saturday(x) && Dates.dayofweekofmonth(x) == 3
is_third_sunday_of_month(x::TimeType) = is_sunday(x) && Dates.dayofweekofmonth(x) == 3

is_fourth_monday_of_month(x::TimeType) = is_monday(x) && Dates.dayofweekofmonth(x) == 4
is_fourth_tuesday_of_month(x::TimeType) = is_tuesday(x) && Dates.dayofweekofmonth(x) == 4
is_fourth_wednesday_of_month(x::TimeType) = is_wednesday(x) && Dates.dayofweekofmonth(x) == 4
is_fourth_thursday_of_month(x::TimeType) = is_thursday(x) && Dates.dayofweekofmonth(x) == 4
is_fourth_friday_of_month(x::TimeType) = is_friday(x) && Dates.dayofweekofmonth(x) == 4
is_fourth_saturday_of_month(x::TimeType) = is_saturday(x) && Dates.dayofweekofmonth(x) == 4
is_fourth_sunday_of_month(x::TimeType) = is_sunday(x) && Dates.dayofweekofmonth(x) == 4

is_fifth_monday_of_month(x::TimeType) = is_monday(x) && Dates.dayofweekofmonth(x) == 5
is_fifth_tuesday_of_month(x::TimeType) = is_tuesday(x) && Dates.dayofweekofmonth(x) == 5
is_fifth_wednesday_of_month(x::TimeType) = is_wednesday(x) && Dates.dayofweekofmonth(x) == 5
is_fifth_thursday_of_month(x::TimeType) = is_thursday(x) && Dates.dayofweekofmonth(x) == 5
is_fifth_friday_of_month(x::TimeType) = is_friday(x) && Dates.dayofweekofmonth(x) == 5
is_fifth_saturday_of_month(x::TimeType) = is_saturday(x) && Dates.dayofweekofmonth(x) == 5
is_fifth_sunday_of_month(x::TimeType) = is_sunday(x) && Dates.dayofweekofmonth(x) == 5

is_last_monday_of_month(x::TimeType) = is_monday(x) && Dates.dayofweekofmonth(x) == Dates.daysofweekinmonth(x)
is_last_tuesday_of_month(x::TimeType) = is_tuesday(x) && Dates.dayofweekofmonth(x) == Dates.daysofweekinmonth(x)
is_last_wednesday_of_month(x::TimeType) = is_wednesday(x) && Dates.dayofweekofmonth(x) == Dates.daysofweekinmonth(x)
is_last_thursday_of_month(x::TimeType) = is_thursday(x) && Dates.dayofweekofmonth(x) == Dates.daysofweekinmonth(x)
is_last_friday_of_month(x::TimeType) = is_friday(x) && Dates.dayofweekofmonth(x) == Dates.daysofweekinmonth(x)
is_last_saturday_of_month(x::TimeType) = is_saturday(x) && Dates.dayofweekofmonth(x) == Dates.daysofweekinmonth(x)
is_last_sunday_of_month(x::TimeType) = is_sunday(x) && Dates.dayofweekofmonth(x) == Dates.daysofweekinmonth(x)

is_third_monday_of_january(x::TimeType) = is_january(x) && is_third_monday_of_month(x)
is_first_monday_of_june(x::TimeType) = is_june(x) && is_first_monday_of_month(x)
is_first_monday_of_september(x::TimeType) = is_september(x) && is_first_monday_of_month(x)
is_fourth_thursday_of_november(x::TimeType) = is_november(x) && is_fourth_thursday_of_month(x)

is_january_1st(x::TimeType) = is_january(x) && is_day(x, 1)
is_january_2nd(x::TimeType) = is_january(x) && is_day(x, 2)
is_january_3rd(x::TimeType) = is_january(x) && is_day(x, 3)
is_january_4th(x::TimeType) = is_january(x) && is_day(x, 4)
is_january_5th(x::TimeType) = is_january(x) && is_day(x, 5)
is_january_6th(x::TimeType) = is_january(x) && is_day(x, 6)
is_january_7th(x::TimeType) = is_january(x) && is_day(x, 7)
is_january_8th(x::TimeType) = is_january(x) && is_day(x, 8)
is_january_9th(x::TimeType) = is_january(x) && is_day(x, 9)
is_january_10th(x::TimeType) = is_january(x) && is_day(x, 10)
is_january_11th(x::TimeType) = is_january(x) && is_day(x, 11)
is_january_12th(x::TimeType) = is_january(x) && is_day(x, 12)
is_january_13th(x::TimeType) = is_january(x) && is_day(x, 13)
is_january_14th(x::TimeType) = is_january(x) && is_day(x, 14)
is_january_15th(x::TimeType) = is_january(x) && is_day(x, 15)
is_january_16th(x::TimeType) = is_january(x) && is_day(x, 16)
is_january_17th(x::TimeType) = is_january(x) && is_day(x, 17)
is_january_18th(x::TimeType) = is_january(x) && is_day(x, 18)
is_january_19th(x::TimeType) = is_january(x) && is_day(x, 19)
is_january_20th(x::TimeType) = is_january(x) && is_day(x, 20)
is_january_21st(x::TimeType) = is_january(x) && is_day(x, 21)
is_january_22nd(x::TimeType) = is_january(x) && is_day(x, 22)
is_january_23rd(x::TimeType) = is_january(x) && is_day(x, 23)
is_january_24th(x::TimeType) = is_january(x) && is_day(x, 24)
is_january_25th(x::TimeType) = is_january(x) && is_day(x, 25)
is_january_26th(x::TimeType) = is_january(x) && is_day(x, 26)
is_january_27th(x::TimeType) = is_january(x) && is_day(x, 27)
is_january_28th(x::TimeType) = is_january(x) && is_day(x, 28)
is_january_29th(x::TimeType) = is_january(x) && is_day(x, 29)
is_january_30th(x::TimeType) = is_january(x) && is_day(x, 30)
is_january_31st(x::TimeType) = is_january(x) && is_day(x, 31)

is_february_1st(x::TimeType) = is_february(x) && is_day(x, 1)
is_february_2nd(x::TimeType) = is_february(x) && is_day(x, 2)
is_february_3rd(x::TimeType) = is_february(x) && is_day(x, 3)
is_february_4th(x::TimeType) = is_february(x) && is_day(x, 4)
is_february_5th(x::TimeType) = is_february(x) && is_day(x, 5)
is_february_6th(x::TimeType) = is_february(x) && is_day(x, 6)
is_february_7th(x::TimeType) = is_february(x) && is_day(x, 7)
is_february_8th(x::TimeType) = is_february(x) && is_day(x, 8)
is_february_9th(x::TimeType) = is_february(x) && is_day(x, 9)
is_february_10th(x::TimeType) = is_february(x) && is_day(x, 10)
is_february_11th(x::TimeType) = is_february(x) && is_day(x, 11)
is_february_12th(x::TimeType) = is_february(x) && is_day(x, 12)
is_february_13th(x::TimeType) = is_february(x) && is_day(x, 13)
is_february_14th(x::TimeType) = is_february(x) && is_day(x, 14)
is_february_15th(x::TimeType) = is_february(x) && is_day(x, 15)
is_february_16th(x::TimeType) = is_february(x) && is_day(x, 16)
is_february_17th(x::TimeType) = is_february(x) && is_day(x, 17)
is_february_18th(x::TimeType) = is_february(x) && is_day(x, 18)
is_february_19th(x::TimeType) = is_february(x) && is_day(x, 19)
is_february_20th(x::TimeType) = is_february(x) && is_day(x, 20)
is_february_21st(x::TimeType) = is_february(x) && is_day(x, 21)
is_february_22nd(x::TimeType) = is_february(x) && is_day(x, 22)
is_february_23rd(x::TimeType) = is_february(x) && is_day(x, 23)
is_february_24th(x::TimeType) = is_february(x) && is_day(x, 24)
is_february_25th(x::TimeType) = is_february(x) && is_day(x, 25)
is_february_26th(x::TimeType) = is_february(x) && is_day(x, 26)
is_february_27th(x::TimeType) = is_february(x) && is_day(x, 27)
is_february_28th(x::TimeType) = is_february(x) && is_day(x, 28)

is_march_1st(x::TimeType) = is_march(x) && is_day(x, 1)
is_march_2nd(x::TimeType) = is_march(x) && is_day(x, 2)
is_march_3rd(x::TimeType) = is_march(x) && is_day(x, 3)
is_march_4th(x::TimeType) = is_march(x) && is_day(x, 4)
is_march_5th(x::TimeType) = is_march(x) && is_day(x, 5)
is_march_6th(x::TimeType) = is_march(x) && is_day(x, 6)
is_march_7th(x::TimeType) = is_march(x) && is_day(x, 7)
is_march_8th(x::TimeType) = is_march(x) && is_day(x, 8)
is_march_9th(x::TimeType) = is_march(x) && is_day(x, 9)
is_march_10th(x::TimeType) = is_march(x) && is_day(x, 10)
is_march_11th(x::TimeType) = is_march(x) && is_day(x, 11)
is_march_12th(x::TimeType) = is_march(x) && is_day(x, 12)
is_march_13th(x::TimeType) = is_march(x) && is_day(x, 13)
is_march_14th(x::TimeType) = is_march(x) && is_day(x, 14)
is_march_15th(x::TimeType) = is_march(x) && is_day(x, 15)
is_march_16th(x::TimeType) = is_march(x) && is_day(x, 16)
is_march_17th(x::TimeType) = is_march(x) && is_day(x, 17)
is_march_18th(x::TimeType) = is_march(x) && is_day(x, 18)
is_march_19th(x::TimeType) = is_march(x) && is_day(x, 19)
is_march_20th(x::TimeType) = is_march(x) && is_day(x, 20)
is_march_21st(x::TimeType) = is_march(x) && is_day(x, 21)
is_march_22nd(x::TimeType) = is_march(x) && is_day(x, 22)
is_march_23rd(x::TimeType) = is_march(x) && is_day(x, 23)
is_march_24th(x::TimeType) = is_march(x) && is_day(x, 24)
is_march_25th(x::TimeType) = is_march(x) && is_day(x, 25)
is_march_26th(x::TimeType) = is_march(x) && is_day(x, 26)
is_march_27th(x::TimeType) = is_march(x) && is_day(x, 27)
is_march_28th(x::TimeType) = is_march(x) && is_day(x, 28)
is_march_29th(x::TimeType) = is_march(x) && is_day(x, 29)
is_march_30th(x::TimeType) = is_march(x) && is_day(x, 30)
is_march_31st(x::TimeType) = is_march(x) && is_day(x, 31)

is_april_1st(x::TimeType) = is_april(x) && is_day(x, 1)
is_april_2nd(x::TimeType) = is_april(x) && is_day(x, 2)
is_april_3rd(x::TimeType) = is_april(x) && is_day(x, 3)
is_april_4th(x::TimeType) = is_april(x) && is_day(x, 4)
is_april_5th(x::TimeType) = is_april(x) && is_day(x, 5)
is_april_6th(x::TimeType) = is_april(x) && is_day(x, 6)
is_april_7th(x::TimeType) = is_april(x) && is_day(x, 7)
is_april_8th(x::TimeType) = is_april(x) && is_day(x, 8)
is_april_9th(x::TimeType) = is_april(x) && is_day(x, 9)
is_april_10th(x::TimeType) = is_april(x) && is_day(x, 10)
is_april_11th(x::TimeType) = is_april(x) && is_day(x, 11)
is_april_12th(x::TimeType) = is_april(x) && is_day(x, 12)
is_april_13th(x::TimeType) = is_april(x) && is_day(x, 13)
is_april_14th(x::TimeType) = is_april(x) && is_day(x, 14)
is_april_15th(x::TimeType) = is_april(x) && is_day(x, 15)
is_april_16th(x::TimeType) = is_april(x) && is_day(x, 16)
is_april_17th(x::TimeType) = is_april(x) && is_day(x, 17)
is_april_18th(x::TimeType) = is_april(x) && is_day(x, 18)
is_april_19th(x::TimeType) = is_april(x) && is_day(x, 19)
is_april_20th(x::TimeType) = is_april(x) && is_day(x, 20)
is_april_21st(x::TimeType) = is_april(x) && is_day(x, 21)
is_april_22nd(x::TimeType) = is_april(x) && is_day(x, 22)
is_april_23rd(x::TimeType) = is_april(x) && is_day(x, 23)
is_april_24th(x::TimeType) = is_april(x) && is_day(x, 24)
is_april_25th(x::TimeType) = is_april(x) && is_day(x, 25)
is_april_26th(x::TimeType) = is_april(x) && is_day(x, 26)
is_april_27th(x::TimeType) = is_april(x) && is_day(x, 27)
is_april_28th(x::TimeType) = is_april(x) && is_day(x, 28)
is_april_29th(x::TimeType) = is_april(x) && is_day(x, 29)
is_april_30th(x::TimeType) = is_april(x) && is_day(x, 30)

is_may_1st(x::TimeType) = is_may(x) && is_day(x, 1)
is_may_2nd(x::TimeType) = is_may(x) && is_day(x, 2)
is_may_3rd(x::TimeType) = is_may(x) && is_day(x, 3)
is_may_4th(x::TimeType) = is_may(x) && is_day(x, 4)
is_may_5th(x::TimeType) = is_may(x) && is_day(x, 5)
is_may_6th(x::TimeType) = is_may(x) && is_day(x, 6)
is_may_7th(x::TimeType) = is_may(x) && is_day(x, 7)
is_may_8th(x::TimeType) = is_may(x) && is_day(x, 8)
is_may_9th(x::TimeType) = is_may(x) && is_day(x, 9)
is_may_10th(x::TimeType) = is_may(x) && is_day(x, 10)
is_may_11th(x::TimeType) = is_may(x) && is_day(x, 11)
is_may_12th(x::TimeType) = is_may(x) && is_day(x, 12)
is_may_13th(x::TimeType) = is_may(x) && is_day(x, 13)
is_may_14th(x::TimeType) = is_may(x) && is_day(x, 14)
is_may_15th(x::TimeType) = is_may(x) && is_day(x, 15)
is_may_16th(x::TimeType) = is_may(x) && is_day(x, 16)
is_may_17th(x::TimeType) = is_may(x) && is_day(x, 17)
is_may_18th(x::TimeType) = is_may(x) && is_day(x, 18)
is_may_19th(x::TimeType) = is_may(x) && is_day(x, 19)
is_may_20th(x::TimeType) = is_may(x) && is_day(x, 20)
is_may_21st(x::TimeType) = is_may(x) && is_day(x, 21)
is_may_22nd(x::TimeType) = is_may(x) && is_day(x, 22)
is_may_23rd(x::TimeType) = is_may(x) && is_day(x, 23)
is_may_24th(x::TimeType) = is_may(x) && is_day(x, 24)
is_may_25th(x::TimeType) = is_may(x) && is_day(x, 25)
is_may_26th(x::TimeType) = is_may(x) && is_day(x, 26)
is_may_27th(x::TimeType) = is_may(x) && is_day(x, 27)
is_may_28th(x::TimeType) = is_may(x) && is_day(x, 28)
is_may_29th(x::TimeType) = is_may(x) && is_day(x, 29)
is_may_30th(x::TimeType) = is_may(x) && is_day(x, 30)
is_may_31st(x::TimeType) = is_may(x) && is_day(x, 31)

is_june_1st(x::TimeType) = is_june(x) && is_day(x, 1)
is_june_2nd(x::TimeType) = is_june(x) && is_day(x, 2)
is_june_3rd(x::TimeType) = is_june(x) && is_day(x, 3)
is_june_4th(x::TimeType) = is_june(x) && is_day(x, 4)
is_june_5th(x::TimeType) = is_june(x) && is_day(x, 5)
is_june_6th(x::TimeType) = is_june(x) && is_day(x, 6)
is_june_7th(x::TimeType) = is_june(x) && is_day(x, 7)
is_june_8th(x::TimeType) = is_june(x) && is_day(x, 8)
is_june_9th(x::TimeType) = is_june(x) && is_day(x, 9)
is_june_10th(x::TimeType) = is_june(x) && is_day(x, 10)
is_june_11th(x::TimeType) = is_june(x) && is_day(x, 11)
is_june_12th(x::TimeType) = is_june(x) && is_day(x, 12)
is_june_13th(x::TimeType) = is_june(x) && is_day(x, 13)
is_june_14th(x::TimeType) = is_june(x) && is_day(x, 14)
is_june_15th(x::TimeType) = is_june(x) && is_day(x, 15)
is_june_16th(x::TimeType) = is_june(x) && is_day(x, 16)
is_june_17th(x::TimeType) = is_june(x) && is_day(x, 17)
is_june_18th(x::TimeType) = is_june(x) && is_day(x, 18)
is_june_19th(x::TimeType) = is_june(x) && is_day(x, 19)
is_june_20th(x::TimeType) = is_june(x) && is_day(x, 20)
is_june_21st(x::TimeType) = is_june(x) && is_day(x, 21)
is_june_22nd(x::TimeType) = is_june(x) && is_day(x, 22)
is_june_23rd(x::TimeType) = is_june(x) && is_day(x, 23)
is_june_24th(x::TimeType) = is_june(x) && is_day(x, 24)
is_june_25th(x::TimeType) = is_june(x) && is_day(x, 25)
is_june_26th(x::TimeType) = is_june(x) && is_day(x, 26)
is_june_27th(x::TimeType) = is_june(x) && is_day(x, 27)
is_june_28th(x::TimeType) = is_june(x) && is_day(x, 28)
is_june_29th(x::TimeType) = is_june(x) && is_day(x, 29)
is_june_30th(x::TimeType) = is_june(x) && is_day(x, 30)

is_july_1st(x::TimeType) = is_july(x) && is_day(x, 1)
is_july_2nd(x::TimeType) = is_july(x) && is_day(x, 2)
is_july_3rd(x::TimeType) = is_july(x) && is_day(x, 3)
is_july_4th(x::TimeType) = is_july(x) && is_day(x, 4)
is_july_5th(x::TimeType) = is_july(x) && is_day(x, 5)
is_july_6th(x::TimeType) = is_july(x) && is_day(x, 6)
is_july_7th(x::TimeType) = is_july(x) && is_day(x, 7)
is_july_8th(x::TimeType) = is_july(x) && is_day(x, 8)
is_july_9th(x::TimeType) = is_july(x) && is_day(x, 9)
is_july_10th(x::TimeType) = is_july(x) && is_day(x, 10)
is_july_11th(x::TimeType) = is_july(x) && is_day(x, 11)
is_july_12th(x::TimeType) = is_july(x) && is_day(x, 12)
is_july_13th(x::TimeType) = is_july(x) && is_day(x, 13)
is_july_14th(x::TimeType) = is_july(x) && is_day(x, 14)
is_july_15th(x::TimeType) = is_july(x) && is_day(x, 15)
is_july_16th(x::TimeType) = is_july(x) && is_day(x, 16)
is_july_17th(x::TimeType) = is_july(x) && is_day(x, 17)
is_july_18th(x::TimeType) = is_july(x) && is_day(x, 18)
is_july_19th(x::TimeType) = is_july(x) && is_day(x, 19)
is_july_20th(x::TimeType) = is_july(x) && is_day(x, 20)
is_july_21st(x::TimeType) = is_july(x) && is_day(x, 21)
is_july_22nd(x::TimeType) = is_july(x) && is_day(x, 22)
is_july_23rd(x::TimeType) = is_july(x) && is_day(x, 23)
is_july_24th(x::TimeType) = is_july(x) && is_day(x, 24)
is_july_25th(x::TimeType) = is_july(x) && is_day(x, 25)
is_july_26th(x::TimeType) = is_july(x) && is_day(x, 26)
is_july_27th(x::TimeType) = is_july(x) && is_day(x, 27)
is_july_28th(x::TimeType) = is_july(x) && is_day(x, 28)
is_july_29th(x::TimeType) = is_july(x) && is_day(x, 29)
is_july_30th(x::TimeType) = is_july(x) && is_day(x, 30)
is_july_31st(x::TimeType) = is_july(x) && is_day(x, 31)

is_august_1st(x::TimeType) = is_august(x) && is_day(x, 1)
is_august_2nd(x::TimeType) = is_august(x) && is_day(x, 2)
is_august_3rd(x::TimeType) = is_august(x) && is_day(x, 3)
is_august_4th(x::TimeType) = is_august(x) && is_day(x, 4)
is_august_5th(x::TimeType) = is_august(x) && is_day(x, 5)
is_august_6th(x::TimeType) = is_august(x) && is_day(x, 6)
is_august_7th(x::TimeType) = is_august(x) && is_day(x, 7)
is_august_8th(x::TimeType) = is_august(x) && is_day(x, 8)
is_august_9th(x::TimeType) = is_august(x) && is_day(x, 9)
is_august_10th(x::TimeType) = is_august(x) && is_day(x, 10)
is_august_11th(x::TimeType) = is_august(x) && is_day(x, 11)
is_august_12th(x::TimeType) = is_august(x) && is_day(x, 12)
is_august_13th(x::TimeType) = is_august(x) && is_day(x, 13)
is_august_14th(x::TimeType) = is_august(x) && is_day(x, 14)
is_august_15th(x::TimeType) = is_august(x) && is_day(x, 15)
is_august_16th(x::TimeType) = is_august(x) && is_day(x, 16)
is_august_17th(x::TimeType) = is_august(x) && is_day(x, 17)
is_august_18th(x::TimeType) = is_august(x) && is_day(x, 18)
is_august_19th(x::TimeType) = is_august(x) && is_day(x, 19)
is_august_20th(x::TimeType) = is_august(x) && is_day(x, 20)
is_august_21st(x::TimeType) = is_august(x) && is_day(x, 21)
is_august_22nd(x::TimeType) = is_august(x) && is_day(x, 22)
is_august_23rd(x::TimeType) = is_august(x) && is_day(x, 23)
is_august_24th(x::TimeType) = is_august(x) && is_day(x, 24)
is_august_25th(x::TimeType) = is_august(x) && is_day(x, 25)
is_august_26th(x::TimeType) = is_august(x) && is_day(x, 26)
is_august_27th(x::TimeType) = is_august(x) && is_day(x, 27)
is_august_28th(x::TimeType) = is_august(x) && is_day(x, 28)
is_august_29th(x::TimeType) = is_august(x) && is_day(x, 29)
is_august_30th(x::TimeType) = is_august(x) && is_day(x, 30)

is_september_1st(x::TimeType) = is_september(x) && is_day(x, 1)
is_september_2nd(x::TimeType) = is_september(x) && is_day(x, 2)
is_september_3rd(x::TimeType) = is_september(x) && is_day(x, 3)
is_september_4th(x::TimeType) = is_september(x) && is_day(x, 4)
is_september_5th(x::TimeType) = is_september(x) && is_day(x, 5)
is_september_6th(x::TimeType) = is_september(x) && is_day(x, 6)
is_september_7th(x::TimeType) = is_september(x) && is_day(x, 7)
is_september_8th(x::TimeType) = is_september(x) && is_day(x, 8)
is_september_9th(x::TimeType) = is_september(x) && is_day(x, 9)
is_september_10th(x::TimeType) = is_september(x) && is_day(x, 10)
is_september_11th(x::TimeType) = is_september(x) && is_day(x, 11)
is_september_12th(x::TimeType) = is_september(x) && is_day(x, 12)
is_september_13th(x::TimeType) = is_september(x) && is_day(x, 13)
is_september_14th(x::TimeType) = is_september(x) && is_day(x, 14)
is_september_15th(x::TimeType) = is_september(x) && is_day(x, 15)
is_september_16th(x::TimeType) = is_september(x) && is_day(x, 16)
is_september_17th(x::TimeType) = is_september(x) && is_day(x, 17)
is_september_18th(x::TimeType) = is_september(x) && is_day(x, 18)
is_september_19th(x::TimeType) = is_september(x) && is_day(x, 19)
is_september_20th(x::TimeType) = is_september(x) && is_day(x, 20)
is_september_21st(x::TimeType) = is_september(x) && is_day(x, 21)
is_september_22nd(x::TimeType) = is_september(x) && is_day(x, 22)
is_september_23rd(x::TimeType) = is_september(x) && is_day(x, 23)
is_september_24th(x::TimeType) = is_september(x) && is_day(x, 24)
is_september_25th(x::TimeType) = is_september(x) && is_day(x, 25)
is_september_26th(x::TimeType) = is_september(x) && is_day(x, 26)
is_september_27th(x::TimeType) = is_september(x) && is_day(x, 27)
is_september_28th(x::TimeType) = is_september(x) && is_day(x, 28)
is_september_29th(x::TimeType) = is_september(x) && is_day(x, 29)
is_september_30th(x::TimeType) = is_september(x) && is_day(x, 30)

is_october_1st(x::TimeType) = is_october(x) && is_day(x, 1)
is_october_2nd(x::TimeType) = is_october(x) && is_day(x, 2)
is_october_3rd(x::TimeType) = is_october(x) && is_day(x, 3)
is_october_4th(x::TimeType) = is_october(x) && is_day(x, 4)
is_october_5th(x::TimeType) = is_october(x) && is_day(x, 5)
is_october_6th(x::TimeType) = is_october(x) && is_day(x, 6)
is_october_7th(x::TimeType) = is_october(x) && is_day(x, 7)
is_october_8th(x::TimeType) = is_october(x) && is_day(x, 8)
is_october_9th(x::TimeType) = is_october(x) && is_day(x, 9)
is_october_10th(x::TimeType) = is_october(x) && is_day(x, 10)
is_october_11th(x::TimeType) = is_october(x) && is_day(x, 11)
is_october_12th(x::TimeType) = is_october(x) && is_day(x, 12)
is_october_13th(x::TimeType) = is_october(x) && is_day(x, 13)
is_october_14th(x::TimeType) = is_october(x) && is_day(x, 14)
is_october_15th(x::TimeType) = is_october(x) && is_day(x, 15)
is_october_16th(x::TimeType) = is_october(x) && is_day(x, 16)
is_october_17th(x::TimeType) = is_october(x) && is_day(x, 17)
is_october_18th(x::TimeType) = is_october(x) && is_day(x, 18)
is_october_19th(x::TimeType) = is_october(x) && is_day(x, 19)
is_october_20th(x::TimeType) = is_october(x) && is_day(x, 20)
is_october_21st(x::TimeType) = is_october(x) && is_day(x, 21)
is_october_22nd(x::TimeType) = is_october(x) && is_day(x, 22)
is_october_23rd(x::TimeType) = is_october(x) && is_day(x, 23)
is_october_24th(x::TimeType) = is_october(x) && is_day(x, 24)
is_october_25th(x::TimeType) = is_october(x) && is_day(x, 25)
is_october_26th(x::TimeType) = is_october(x) && is_day(x, 26)
is_october_27th(x::TimeType) = is_october(x) && is_day(x, 27)
is_october_28th(x::TimeType) = is_october(x) && is_day(x, 28)
is_october_29th(x::TimeType) = is_october(x) && is_day(x, 29)
is_october_30th(x::TimeType) = is_october(x) && is_day(x, 30)
is_october_31st(x::TimeType) = is_october(x) && is_day(x, 31)

is_november_1st(x::TimeType) = is_november(x) && is_day(x, 1)
is_november_2nd(x::TimeType) = is_november(x) && is_day(x, 2)
is_november_3rd(x::TimeType) = is_november(x) && is_day(x, 3)
is_november_4th(x::TimeType) = is_november(x) && is_day(x, 4)
is_november_5th(x::TimeType) = is_november(x) && is_day(x, 5)
is_november_10th(x::TimeType) = is_november(x) && is_day(x, 10)
is_november_11th(x::TimeType) = is_november(x) && is_day(x, 11)
is_november_15th(x::TimeType) = is_november(x) && is_day(x, 15)
is_november_20th(x::TimeType) = is_november(x) && is_day(x, 20)
is_november_30th(x::TimeType) = is_november(x) && is_day(x, 30)

is_december_1st(x::TimeType) = is_december(x) && is_day(x, 1)
is_december_2nd(x::TimeType) = is_december(x) && is_day(x, 2)
is_december_3rd(x::TimeType) = is_december(x) && is_day(x, 3)
is_december_4th(x::TimeType) = is_december(x) && is_day(x, 4)
is_december_5th(x::TimeType) = is_december(x) && is_day(x, 5)
is_december_6th(x::TimeType) = is_december(x) && is_day(x, 6)
is_december_7th(x::TimeType) = is_december(x) && is_day(x, 7)
is_december_8th(x::TimeType) = is_december(x) && is_day(x, 8)
is_december_9th(x::TimeType) = is_december(x) && is_day(x, 9)
is_december_10th(x::TimeType) = is_december(x) && is_day(x, 10)
is_december_11th(x::TimeType) = is_december(x) && is_day(x, 11)
is_december_12th(x::TimeType) = is_december(x) && is_day(x, 12)
is_december_13th(x::TimeType) = is_december(x) && is_day(x, 13)
is_december_14th(x::TimeType) = is_december(x) && is_day(x, 14)
is_december_15th(x::TimeType) = is_december(x) && is_day(x, 15)
is_december_16th(x::TimeType) = is_december(x) && is_day(x, 16)
is_december_17th(x::TimeType) = is_december(x) && is_day(x, 17)
is_december_18th(x::TimeType) = is_december(x) && is_day(x, 18)
is_december_19th(x::TimeType) = is_december(x) && is_day(x, 19)
is_december_20th(x::TimeType) = is_december(x) && is_day(x, 20)
is_december_21st(x::TimeType) = is_december(x) && is_day(x, 21)
is_december_22nd(x::TimeType) = is_december(x) && is_day(x, 22)
is_december_23rd(x::TimeType) = is_december(x) && is_day(x, 23)
is_december_24th(x::TimeType) = is_december(x) && is_day(x, 24)
is_december_25th(x::TimeType) = is_december(x) && is_day(x, 25)
is_december_26th(x::TimeType) = is_december(x) && is_day(x, 26)
is_december_27th(x::TimeType) = is_december(x) && is_day(x, 27)
is_december_28th(x::TimeType) = is_december(x) && is_day(x, 28)
is_december_29th(x::TimeType) = is_december(x) && is_day(x, 29)
is_december_30th(x::TimeType) = is_december(x) && is_day(x, 30)
is_december_31st(x::TimeType) = is_december(x) && is_day(x, 31)
